export const ACTIVITY_LOG_DETAIL_REQUEST = 'ACTIVITY_LOG_DETAIL_REQUEST'
export const ACTIVITY_LOG_DETAIL_SUCCESS = 'ACTIVITY_LOG_DETAIL_SUCCESS'
export const ACTIVITY_LOG_DETAIL_FAIL = 'ACTIVITY_LOG_DETAIL_FAIL'
export const ACTIVITY_LOG_DETAIL_RESET = 'ACTIVITY_LOG_DETAIL_RESET'