export const ADD_BATCH_REQUEST = 'ADD_BATCH_REQUEST'
export const ADD_BATCH_SUCCESS = 'ADD_BATCH_SUCCESS'
export const ADD_BATCH_FAIL = 'ADD_BATCH_FAIL'

export const FETCH_ALL_BATCH_REQUEST = 'FETCH_ALL_BATCH_REQUEST'
export const FETCH_ALL_BATCH_SUCCESS = 'FETCH_ALL_BATCH_SUCCESS'
export const FETCH_ALL_BATCH_FAIL = 'FETCH_ALL_BATCH_FAIL'

export const FETCH_BATCH_REQUEST = 'FETCH_BATCH_REQUEST'
export const FETCH_BATCH_SUCCESS = 'FETCH_BATCH_SUCCESS'
export const FETCH_BATCH_FAIL = 'FETCH_BATCH_FAIL'

export const DELETE_BATCH_REQUEST = 'DELETE_BATCH_REQUEST'
export const DELETE_BATCH_SUCCESS = 'DELETE_BATCH_SUCCESS'
export const DELETE_BATCH_FAIL = 'DELETE_BATCH_FAIL'
export const DELETE_BATCH_RESET = 'DELETE_BATCH_RESET'

export const UPDATE_BATCH_REQUEST = 'UPDATE_BATCH_REQUEST'
export const UPDATE_BATCH_SUCCESS = 'UPDATE_BATCH_SUCCESS'
export const UPDATE_BATCH_FAIL = 'UPDATE_BATCH_FAIL'
export const UPDATE_BATCH_RESET = 'UPDATE_BATCH_RESET'
