export const BULK_LEAD_ADD_REQUEST = 'BULK_LEAD_ADD_REQUEST'
export const BULK_LEAD_ADD_SUCCESS = 'BULK_LEAD_ADD_SUCCESS'
export const BULK_LEAD_ADD_FAIL = 'BULK_LEAD_ADD_FAIL'
export const BULK_LEAD_ADD_RESET = 'BULK_LEAD_ADD_RESET'

export const BULK_LEAD_ASSIGN_REQUEST = 'BULK_LEAD_ASSIGN_REQUEST'
export const BULK_LEAD_ASSIGN_SUCCESS = 'BULK_LEAD_ASSIGN_SUCCESS'
export const BULK_LEAD_ASSIGN_FAIL = 'BULK_LEAD_ASSIGN_FAIL'

export const BULK_LEAD_LIST_REQUEST = 'BULK_LEAD_LIST_REQUEST'
export const BULK_LEAD_LIST_SUCCESS = 'BULK_LEAD_LIST_SUCCESS'
export const BULK_LEAD_LIST_FAIL = 'BULK_LEAD_LIST_FAIL'

export const BULK_LEAD_EDIT_REQUEST = 'BULK_LEAD_EDIT_REQUEST'
export const BULK_LEAD_EDIT_SUCCESS = 'BULK_LEAD_EDIT_SUCCESS'
export const BULK_LEAD_EDIT_FAIL = 'BULK_LEAD_EDIT_FAIL'