export const CANCEL_LEAD_ADD_REQUEST = 'CANCEL_LEAD_ADD_REQUEST'
export const CANCEL_LEAD_ADD_SUCCESS = 'CANCEL_LEAD_ADD_SUCCESS'
export const CANCEL_LEAD_ADD_FAIL = 'CANCEL_LEAD_ADD_FAIL'

export const CANCEL_LEAD_LIST_REQUEST = 'CANCEL_LEAD_LIST_REQUEST'
export const CANCEL_LEAD_LIST_SUCCESS = 'CANCEL_LEAD_LIST_SUCCESS'
export const CANCEL_LEAD_LIST_FAIL = 'CANCEL_LEAD_LIST_FAIL'

export const CANCEL_LEAD_DELETE_REQUEST = 'CANCEL_LEAD_DELETE_REQUEST'
export const CANCEL_LEAD_DELETE_SUCCESS = 'CANCEL_LEAD_DELETE_SUCCESS'
export const CANCEL_LEAD_DELETE_FAIL = 'CANCEL_LEAD_DELETE_FAIL'

export const CANCEL_LEAD_UPDATE_REQUEST = 'CANCEL_LEAD_UPDATE_REQUEST'
export const CANCEL_LEAD_UPDATE_SUCCESS = 'CANCEL_LEAD_UPDATE_SUCCESS'
export const CANCEL_LEAD_UPDATE_FAIL = 'CANCEL_LEAD_UPDATE_FAIL'
export const CANCEL_LEAD_UPDATE_RESET = 'CANCEL_LEAD_UPDATE_RESET'

export const CANCEL_LEAD_DETAIL_REQUEST = 'CANCEL_LEAD_DETAIL_REQUEST'
export const CANCEL_LEAD_DETAIL_SUCCESS = 'CANCEL_LEAD_DETAIL_SUCCESS'
export const CANCEL_LEAD_DETAIL_FAIL = 'CANCEL_LEAD_DETAIL_FAIL'
export const CANCEL_LEAD_DETAIL_RESET = 'CANCEL_LEAD_DETAIL_RESET'