export const LEAD_ADD_REQUEST = 'LEAD_ADD_REQUEST'
export const LEAD_ADD_SUCCESS = 'LEAD_ADD_SUCCESS'
export const LEAD_ADD_FAIL = 'LEAD_ADD_FAIL'

export const LEAD_UPDATE_REQUEST = 'LEAD_UPDATE_REQUEST'
export const LEAD_UPDATE_SUCCESS = 'LEAD_UPDATE_SUCCESS'
export const LEAD_UPDATE_FAIL = 'LEAD_UPDATE_FAIL'
export const LEAD_UPDATE_RESET = 'LEAD_UPDATE_RESET'

export const LEAD_DETAILS_REQUEST = 'LEAD_DETAILS_REQUEST'
export const LEAD_DETAILS_SUCCESS = 'LEAD_DETAILS_SUCCESS'
export const LEAD_DETAILS_FAIL = 'LEAD_DETAILS_FAIL'
export const LEAD_DETAILS_RESET = 'LEAD_DETAILS_RESET'

export const LEAD_LIST_REQUEST = 'LEAD_LIST_REQUEST'
export const LEAD_LIST_SUCCESS = 'LEAD_LIST_SUCCESS'
export const LEAD_LIST_FAIL = 'LEAD_LIST_FAIL'

export const CONSULTANT_LEAD_LIST_REQUEST = 'CONSULTANT_LEAD_LIST_REQUEST'
export const CONSULTANT_LEAD_LIST_SUCCESS = 'CONSULTANT_LEAD_LIST_SUCCESS'
export const CONSULTANT_LEAD_LIST_FAIL = 'CONSULTANT_LEAD_LIST_FAIL'

export const MANAGER_LEAD_LIST_REQUEST = 'MANAGER_LEAD_LIST_REQUEST'
export const MANAGER_LEAD_LIST_SUCCESS = 'MANAGER_LEAD_LIST_SUCCESS'
export const MANAGER_LEAD_LIST_FAIL = 'MANAGER_LEAD_LIST_FAIL'

export const TEAMLEAD_LEAD_LIST_REQUEST = 'TEAMLEAD_LEAD_LIST_REQUEST'
export const TEAMLEAD_LEAD_LIST_SUCCESS = 'TEAMLEAD_LEAD_LIST_SUCCESS'
export const TEAMLEAD_LEAD_LIST_FAIL = 'TEAMLEAD_LEAD_LIST_FAIL'

export const LEAD_DELETE_REQUEST = 'LEAD_DELETE_REQUEST'
export const LEAD_DELETE_SUCCESS = 'LEAD_DELETE_SUCCESS'
export const LEAD_DELETE_FAIL = 'LEAD_DELETE_FAIL'

export const BULK_UPLOAD_REQUEST = 'BULK_UPLOAD_REQUEST'
export const BULK_UPLOAD_SUCCESS = 'BULK_UPLOAD_SUCCESS'
export const BULK_UPLOAD_FAIL = 'BULK_UPLOAD_FAIL'

