export const ADD_STUDENT_REQUEST = 'ADD_STUDENT_REQUEST'
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS'
export const ADD_STUDENT_FAIL = 'ADD_STUDENT_FAIL'

export const FETCH_ALL_STUDENT_REQUEST = 'FETCH_ALL_STUDENT_REQUEST'
export const FETCH_ALL_STUDENT_SUCCESS = 'FETCH_ALL_STUDENT_SUCCESS'
export const FETCH_ALL_STUDENT_FAIL = 'FETCH_ALL_STUDENT_FAIL'

export const FETCH_STUDENT_REQUEST = 'FETCH_STUDENT_REQUEST'
export const FETCH_STUDENT_SUCCESS = 'FETCH_STUDENT_SUCCESS'
export const FETCH_STUDENT_FAIL = 'FETCH_STUDENT_FAIL'

export const DELETE_STUDENT_REQUEST = 'DELETE_STUDENT_REQUEST'
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS'
export const DELETE_STUDENT_FAIL = 'DELETE_STUDENT_FAIL'
export const DELETE_STUDENT_RESET = 'DELETE_STUDENT_RESET'

export const UPDATE_STUDENT_REQUEST = 'UPDATE_STUDENT_REQUEST'
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS'
export const UPDATE_STUDENT_FAIL = 'UPDATE_STUDENT_FAIL'
export const UPDATE_STUDENT_RESET = 'UPDATE_STUDENT_RESET'
