export const ADD_TEAM_REQUEST = 'ADD_TEAM_REQUEST'
export const ADD_TEAM_SUCCESS = 'ADD_TEAM_SUCCESS'
export const ADD_TEAM_FAIL = 'ADD_TEAM_FAIL'
export const ADD_TEAM_RESET = 'ADD_TEAM_RESET'

export const FETCH_TEAM_LIST_REQUEST = 'FETCH_TEAM_LIST_REQUEST'
export const FETCH_TEAM_LIST_SUCCESS = 'FETCH_TEAM_LIST_SUCCESS'
export const FETCH_TEAM_LIST_FAIL = 'FETCH_TEAM_LIST_FAIL'

export const TEAM_DETAILS_REQUEST = 'TEAM_DETAILS_REQUEST'
export const TEAM_DETAILS_SUCCESS = 'TEAM_DETAILS_SUCCESS'
export const TEAM_DETAILS_FAIL = 'TEAM_DETAILS_FAIL'

export const UPDATE_TEAM_REQUEST = 'UPDATE_TEAM_REQUEST'
export const UPDATE_TEAM_SUCCESS = 'UPDATE_TEAM_SUCCESS'
export const UPDATE_TEAM_FAIL = 'UPDATE_TEAM_FAIL'
export const UPDATE_TEAM_RESET = 'UPDATE_TEAM_RESET'

export const DELETE_TEAM_REQUEST = 'DELETE_TEAM_REQUEST'
export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS'
export const DELETE_TEAM_FAIL = 'DELETE_TEAM_FAIL'
export const DELETE_TEAM_RESET = 'DELETE_TEAM_RESET'