/* Login */
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

/* Add User */
export const ADD_USER_REQUEST = 'ADD_USER_REQUEST'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAIL = 'ADD_USER_FAIL'
export const ADD_USER_RESET = 'ADD_USER_RESET'

/* Add Manager */
export const ADD_MANAGER_REQUEST = 'ADD_MANAGER_REQUEST'
export const ADD_MANAGER_SUCCESS = 'ADD_MANAGER_SUCCESS'
export const ADD_MANAGER_FAIL = 'ADD_MANAGER_FAIL'

/* Add TeamLead */
export const ADD_TEAMLEAD_REQUEST = 'ADD_TEAMLEAD_REQUEST'
export const ADD_TEAMLEAD_SUCCESS = 'ADD_TEAMLEAD_SUCCESS'
export const ADD_TEAMLEAD_FAIL = 'ADD_TEAMLEAD_FAIL'

/* Add CHANNEL PATNER MANAGER */
export const ADD_CPM_REQUEST = 'ADD_CPM_REQUEST'
export const ADD_CPM_SUCCESS = 'ADD_CPM_SUCCESS'
export const ADD_CPM_FAIL = 'ADD_CPM_FAIL'

/* Add CHANNEL PATNER */
export const ADD_CP_REQUEST = 'ADD_CP_REQUEST'
export const ADD_CP_SUCCESS = 'ADD_CP_SUCCESS'
export const ADD_CP_FAIL = 'ADD_CP_FAIL'

/* Managers details */
export const MANAGERS_DETAILS_REQUEST = 'MANAGERS_DETAILS_REQUEST'
export const MANAGERS_DETAILS_SUCCESS = 'MANAGERS_DETAILS_SUCCESS'
export const MANAGERS_DETAILS_FAIL = 'MANAGERS_DETAILS_FAIL'

/* TeamLeads details */
export const TEAMLEADS_DETAILS_REQUEST = 'TEAMLEADS_DETAILS_REQUEST'
export const TEAMLEADS_DETAILS_SUCCESS = 'TEAMLEADS_DETAILS_SUCCESS'
export const TEAMLEADS_DETAILS_FAIL = 'TEAMLEADS_DETAILS_FAIL'

/* ASMs details */
export const ASMS_DETAILS_REQUEST = 'ASMS_DETAILS_REQUEST'
export const ASMS_DETAILS_SUCCESS = 'ASMS_DETAILS_SUCCESS'
export const ASMS_DETAILS_FAIL = 'ASMS_DETAILS_FAIL'

/* Consultant details */
export const CONSULTANTS_DETAILS_REQUEST = 'CONSULTANTS_DETAILS_REQUEST'
export const CONSULTANTS_DETAILS_SUCCESS = 'CONSULTANTS_DETAILS_SUCCESS'
export const CONSULTANTS_DETAILS_FAIL = 'CONSULTANTS_DETAILS_FAIL'

/* Remove User */
export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

/* Update User */
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'

/* User List */
export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'

/* User List */
export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST'
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS'
export const USER_DETAIL_FAIL = 'USER_DETAIL_FAIL'

/* TeamLeads under Manager details */
export const MANAGER_TEAMLEADS_DETAILS_REQUEST = 'MANAGER_TEAMLEADS_DETAILS_REQUEST'
export const MANAGER_TEAMLEADS_DETAILS_SUCCESS = 'MANAGER_TEAMLEADS_DETAILS_SUCCESS'
export const MANAGER_TEAMLEADS_DETAILS_FAIL = 'MANAGER_TEAMLEADS_DETAILS_FAIL'

/* Consultants under TeamLead details */
export const TEAMLEAD_CONSULTANTS_DETAILS_REQUEST = 'TEAMLEAD_CONSULTANTS_DETAILS_REQUEST'
export const TEAMLEAD_CONSULTANTS_DETAILS_SUCCESS = 'TEAMLEAD_CONSULTANTS_DETAILS_SUCCESS'
export const TEAMLEAD_CONSULTANTS_DETAILS_FAIL = 'TEAMLEAD_CONSULTANTS_DETAILS_FAIL'

/* Consultants under Manager details */
export const MANAGER_CONSULTANTS_DETAILS_REQUEST = 'MANAGER_CONSULTANTS_DETAILS_REQUEST'
export const MANAGER_CONSULTANTS_DETAILS_SUCCESS = 'MANAGER_CONSULTANTS_DETAILS_SUCCESS'
export const MANAGER_CONSULTANTS_DETAILS_FAIL = 'MANAGER_CONSULTANTS_DETAILS_FAIL'

